# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import requests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 50, 131, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 110, 131, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(145, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 170, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 230, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 170, 131, 41))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.cekme)
        self.comboBox.addItem("USD")
        self.comboBox.addItem("AFN")
        self.comboBox.addItem("ALL")
        self.comboBox.addItem("AMD")
        self.comboBox.addItem("ANG")
        self.comboBox.addItem("AOA")
        self.comboBox.addItem("ARS")
        self.comboBox.addItem("AUD")
        self.comboBox.addItem("AWG")
        self.comboBox.addItem("AZN")
        self.comboBox.addItem("BAM")
        self.comboBox.addItem("BBD")
        self.comboBox.addItem("BDT")
        self.comboBox.addItem("BGN")
        self.comboBox.addItem("BHD")
        self.comboBox.addItem("BIF")
        self.comboBox.addItem("BMD")
        self.comboBox.addItem("BND")
        self.comboBox.addItem("BOB")
        self.comboBox.addItem("BRL")
        self.comboBox.addItem("BSD")
        self.comboBox.addItem("BTC")
        self.comboBox.addItem("BTN")
        self.comboBox.addItem("BWP")
        self.comboBox.addItem("BYN")
        self.comboBox.addItem("BYR")
        self.comboBox.addItem("BZD")
        self.comboBox.addItem("CAD")
        self.comboBox.addItem("CDF")
        self.comboBox.addItem("CHF")
        self.comboBox.addItem("CLF")
        self.comboBox.addItem("CLP")
        self.comboBox.addItem("CNY")
        self.comboBox.addItem("COP")
        self.comboBox.addItem("CRC")
        self.comboBox.addItem("CUC")
        self.comboBox.addItem("CUP")
        self.comboBox.addItem("CVE")
        self.comboBox.addItem("CZK")
        self.comboBox.addItem("DJF")
        self.comboBox.addItem("DKK")
        self.comboBox.addItem("DOP")
        self.comboBox.addItem("DZD")
        self.comboBox.addItem("EGP")
        self.comboBox.addItem("ERN")
        self.comboBox.addItem("ETB")
        self.comboBox.addItem("EUR")
        self.comboBox.addItem("FJD")
        self.comboBox.addItem("FKP")
        self.comboBox.addItem("GBP")
        self.comboBox.addItem("GEL")
        self.comboBox.addItem("GGP")
        self.comboBox.addItem("GHS")
        self.comboBox.addItem("GIP")
        self.comboBox.addItem("GMD")
        self.comboBox.addItem("GNF")
        self.comboBox.addItem("GTQ")
        self.comboBox.addItem("GYD")
        self.comboBox.addItem("HKD")
        self.comboBox.addItem("HNL")
        self.comboBox.addItem("HRK")
        self.comboBox.addItem("HTG")
        self.comboBox.addItem("HUF")
        self.comboBox.addItem("IDR")
        self.comboBox.addItem("ILS")
        self.comboBox.addItem("IMP")
        self.comboBox.addItem("INR")
        self.comboBox.addItem("IQD")
        self.comboBox.addItem("IRR")
        self.comboBox.addItem("ISK")
        self.comboBox.addItem("JEP")
        self.comboBox.addItem("JMD")
        self.comboBox.addItem("JOD")
        self.comboBox.addItem("JPY")
        self.comboBox.addItem("KES")
        self.comboBox.addItem("KGS")
        self.comboBox.addItem("KHR")
        self.comboBox.addItem("KMF")
        self.comboBox.addItem("KPW")
        self.comboBox.addItem("KRW")
        self.comboBox.addItem("KWD")
        self.comboBox.addItem("KYD")
        self.comboBox.addItem("KZT")
        self.comboBox.addItem("LAK")
        self.comboBox.addItem("LBP")
        self.comboBox.addItem("LKR")
        self.comboBox.addItem("LRD")
        self.comboBox.addItem("LSL")
        self.comboBox.addItem("LTL")
        self.comboBox.addItem("LVL")
        self.comboBox.addItem("LYD")
        self.comboBox.addItem("MAD")
        self.comboBox.addItem("MDL")
        self.comboBox.addItem("MGA")
        self.comboBox.addItem("MKD")
        self.comboBox.addItem("MMK")
        self.comboBox.addItem("MNT")
        self.comboBox.addItem("MOP")
        self.comboBox.addItem("MRO")
        self.comboBox.addItem("MUR")
        self.comboBox.addItem("MVR")
        self.comboBox.addItem("MWK")
        self.comboBox.addItem("MXN")
        self.comboBox.addItem("MYR")
        self.comboBox.addItem("MZN")
        self.comboBox.addItem("NAD")
        self.comboBox.addItem("NGN")
        self.comboBox.addItem("NIO")
        self.comboBox.addItem("NOK")
        self.comboBox.addItem("NPR")
        self.comboBox.addItem("NZD")
        self.comboBox.addItem("OMR")
        self.comboBox.addItem("PAB")
        self.comboBox.addItem("PEN")
        self.comboBox.addItem("PGK")
        self.comboBox.addItem("PHP")
        self.comboBox.addItem("PKR")
        self.comboBox.addItem("PLN")
        self.comboBox.addItem("PYG")
        self.comboBox.addItem("QAR")
        self.comboBox.addItem("RON")
        self.comboBox.addItem("RSD")
        self.comboBox.addItem("RUB")
        self.comboBox.addItem("RWF")
        self.comboBox.addItem("SAR")
        self.comboBox.addItem("SBD")
        self.comboBox.addItem("SCR")
        self.comboBox.addItem("SDG")
        self.comboBox.addItem("SEK")
        self.comboBox.addItem("SGD")
        self.comboBox.addItem("SHP")
        self.comboBox.addItem("SLL")
        self.comboBox.addItem("SOS")
        self.comboBox.addItem("SRD")
        self.comboBox.addItem("STD")
        self.comboBox.addItem("SVC")
        self.comboBox.addItem("SYP")
        self.comboBox.addItem("SZL")
        self.comboBox.addItem("THB")
        self.comboBox.addItem("TJS")
        self.comboBox.addItem("TMT")
        self.comboBox.addItem("TND")
        self.comboBox.addItem("TOP")
        self.comboBox.addItem("TRY")
        self.comboBox.addItem("TTD")
        self.comboBox.addItem("TWD")
        self.comboBox.addItem("TZS")
        self.comboBox.addItem("UAH")
        self.comboBox.addItem("UGX")
        self.comboBox.addItem("USD")
        self.comboBox.addItem("UYU")
        self.comboBox.addItem("UZS")
        self.comboBox.addItem("VEF")
        self.comboBox.addItem("VND")
        self.comboBox.addItem("VUV")
        self.comboBox.addItem("WST")
        self.comboBox.addItem("XAF")
        self.comboBox.addItem("XCD")
        self.comboBox.addItem("XDR")
        self.comboBox.addItem("XOF")
        self.comboBox.addItem("XPF")
        self.comboBox.addItem("YER")
        self.comboBox.addItem("ZAR")
        self.comboBox.addItem("ZMK")
        self.comboBox.addItem("ZMW")
        self.comboBox.addItem("ZWL")
        self.comboBox_2.addItem("USD")
        self.comboBox_2.addItem("AFN")
        self.comboBox_2.addItem("ALL")
        self.comboBox_2.addItem("AMD")
        self.comboBox_2.addItem("ANG")
        self.comboBox_2.addItem("AOA")
        self.comboBox_2.addItem("ARS")
        self.comboBox_2.addItem("AUD")
        self.comboBox_2.addItem("AWG")
        self.comboBox_2.addItem("AZN")
        self.comboBox_2.addItem("BAM")
        self.comboBox_2.addItem("BBD")
        self.comboBox_2.addItem("BDT")
        self.comboBox_2.addItem("BGN")
        self.comboBox_2.addItem("BHD")
        self.comboBox_2.addItem("BIF")
        self.comboBox_2.addItem("BMD")
        self.comboBox_2.addItem("BND")
        self.comboBox_2.addItem("BOB")
        self.comboBox_2.addItem("BRL")
        self.comboBox_2.addItem("BSD")
        self.comboBox_2.addItem("BTC")
        self.comboBox_2.addItem("BTN")
        self.comboBox_2.addItem("BWP")
        self.comboBox_2.addItem("BYN")
        self.comboBox_2.addItem("BYR")
        self.comboBox_2.addItem("BZD")
        self.comboBox_2.addItem("CAD")
        self.comboBox_2.addItem("CDF")
        self.comboBox_2.addItem("CHF")
        self.comboBox_2.addItem("CLF")
        self.comboBox_2.addItem("CLP")
        self.comboBox_2.addItem("CNY")
        self.comboBox_2.addItem("COP")
        self.comboBox_2.addItem("CRC")
        self.comboBox_2.addItem("CUC")
        self.comboBox_2.addItem("CUP")
        self.comboBox_2.addItem("CVE")
        self.comboBox_2.addItem("CZK")
        self.comboBox_2.addItem("DJF")
        self.comboBox_2.addItem("DKK")
        self.comboBox_2.addItem("DOP")
        self.comboBox_2.addItem("DZD")
        self.comboBox_2.addItem("EGP")
        self.comboBox_2.addItem("ERN")
        self.comboBox_2.addItem("ETB")
        self.comboBox_2.addItem("EUR")
        self.comboBox_2.addItem("FJD")
        self.comboBox_2.addItem("FKP")
        self.comboBox_2.addItem("GBP")
        self.comboBox_2.addItem("GEL")
        self.comboBox_2.addItem("GGP")
        self.comboBox_2.addItem("GHS")
        self.comboBox_2.addItem("GIP")
        self.comboBox_2.addItem("GMD")
        self.comboBox_2.addItem("GNF")
        self.comboBox_2.addItem("GTQ")
        self.comboBox_2.addItem("GYD")
        self.comboBox_2.addItem("HKD")
        self.comboBox_2.addItem("HNL")
        self.comboBox_2.addItem("HRK")
        self.comboBox_2.addItem("HTG")
        self.comboBox_2.addItem("HUF")
        self.comboBox_2.addItem("IDR")
        self.comboBox_2.addItem("ILS")
        self.comboBox_2.addItem("IMP")
        self.comboBox_2.addItem("INR")
        self.comboBox_2.addItem("IQD")
        self.comboBox_2.addItem("IRR")
        self.comboBox_2.addItem("ISK")
        self.comboBox_2.addItem("JEP")
        self.comboBox_2.addItem("JMD")
        self.comboBox_2.addItem("JOD")
        self.comboBox_2.addItem("JPY")
        self.comboBox_2.addItem("KES")
        self.comboBox_2.addItem("KGS")
        self.comboBox_2.addItem("KHR")
        self.comboBox_2.addItem("KMF")
        self.comboBox_2.addItem("KPW")
        self.comboBox_2.addItem("KRW")
        self.comboBox_2.addItem("KWD")
        self.comboBox_2.addItem("KYD")
        self.comboBox_2.addItem("KZT")
        self.comboBox_2.addItem("LAK")
        self.comboBox_2.addItem("LBP")
        self.comboBox_2.addItem("LKR")
        self.comboBox_2.addItem("LRD")
        self.comboBox_2.addItem("LSL")
        self.comboBox_2.addItem("LTL")
        self.comboBox_2.addItem("LVL")
        self.comboBox_2.addItem("LYD")
        self.comboBox_2.addItem("MAD")
        self.comboBox_2.addItem("MDL")
        self.comboBox_2.addItem("MGA")
        self.comboBox_2.addItem("MKD")
        self.comboBox_2.addItem("MMK")
        self.comboBox_2.addItem("MNT")
        self.comboBox_2.addItem("MOP")
        self.comboBox_2.addItem("MRO")
        self.comboBox_2.addItem("MUR")
        self.comboBox_2.addItem("MVR")
        self.comboBox_2.addItem("MWK")
        self.comboBox_2.addItem("MXN")
        self.comboBox_2.addItem("MYR")
        self.comboBox_2.addItem("MZN")
        self.comboBox_2.addItem("NAD")
        self.comboBox_2.addItem("NGN")
        self.comboBox_2.addItem("NIO")
        self.comboBox_2.addItem("NOK")
        self.comboBox_2.addItem("NPR")
        self.comboBox_2.addItem("NZD")
        self.comboBox_2.addItem("OMR")
        self.comboBox_2.addItem("PAB")
        self.comboBox_2.addItem("PEN")
        self.comboBox_2.addItem("PGK")
        self.comboBox_2.addItem("PHP")
        self.comboBox_2.addItem("PKR")
        self.comboBox_2.addItem("PLN")
        self.comboBox_2.addItem("PYG")
        self.comboBox_2.addItem("QAR")
        self.comboBox_2.addItem("RON")
        self.comboBox_2.addItem("RSD")
        self.comboBox_2.addItem("RUB")
        self.comboBox_2.addItem("RWF")
        self.comboBox_2.addItem("SAR")
        self.comboBox_2.addItem("SBD")
        self.comboBox_2.addItem("SCR")
        self.comboBox_2.addItem("SDG")
        self.comboBox_2.addItem("SEK")
        self.comboBox_2.addItem("SGD")
        self.comboBox_2.addItem("SHP")
        self.comboBox_2.addItem("SLL")
        self.comboBox_2.addItem("SOS")
        self.comboBox_2.addItem("SRD")
        self.comboBox_2.addItem("STD")
        self.comboBox_2.addItem("SVC")
        self.comboBox_2.addItem("SYP")
        self.comboBox_2.addItem("SZL")
        self.comboBox_2.addItem("THB")
        self.comboBox_2.addItem("TJS")
        self.comboBox_2.addItem("TMT")
        self.comboBox_2.addItem("TND")
        self.comboBox_2.addItem("TOP")
        self.comboBox_2.addItem("TRY")
        self.comboBox_2.addItem("TTD")
        self.comboBox_2.addItem("TWD")
        self.comboBox_2.addItem("TZS")
        self.comboBox_2.addItem("UAH")
        self.comboBox_2.addItem("UGX")
        self.comboBox_2.addItem("USD")
        self.comboBox_2.addItem("UYU")
        self.comboBox_2.addItem("UZS")
        self.comboBox_2.addItem("VEF")
        self.comboBox_2.addItem("VND")
        self.comboBox_2.addItem("VUV")
        self.comboBox_2.addItem("WST")
        self.comboBox_2.addItem("XAF")
        self.comboBox_2.addItem("XCD")
        self.comboBox_2.addItem("XDR")
        self.comboBox_2.addItem("XOF")
        self.comboBox_2.addItem("XPF")
        self.comboBox_2.addItem("YER")
        self.comboBox_2.addItem("ZAR")
        self.comboBox_2.addItem("ZMK")
        self.comboBox_2.addItem("ZMW")
        self.comboBox_2.addItem("ZWL")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Program"))
        self.label.setText(_translate("MainWindow", "From:"))
        self.label_2.setText(_translate("MainWindow", "To:"))
        self.label_3.setText(_translate("MainWindow", "Amount:"))
        self.pushButton.setText(_translate("MainWindow", "Go!"))

    def cekme(self):

        url = "http://data.fixer.io/api/latest?access_key=805b9fd81e32ad142cc3076075ae80e1"
        response = requests.get(url)
        json_verisi = response.json()

        bir = self.comboBox.currentText()
        iki = self.comboBox_2.currentText()

        miktar = self.lineEdit.text()
        miktar = float(miktar)

        deger = (json_verisi["rates"][iki] * miktar) / (json_verisi["rates"][bir])
        self.label_4.setText("{} {} = {} {}".format(miktar, bir, deger, iki))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

